-- Наполнение таблицы master_listings реальными мастерами с фото
-- Запусти этот файл в SQL Editor в панели Supabase

WITH master_seed (
  full_name,
  phone,
  avatar_url,
  bio,
  service_categories,
  working_districts,
  experience_years,
  average_rating,
  total_reviews,
  price_min,
  price_max,
  latitude,
  longitude,
  ranking_score,
  completed_orders,
  cancelled_orders,
  response_time_avg,
  repeat_clients,
  complaints,
  quality_flag,
  is_top_master,
  is_active
) AS (
  VALUES
    (
      'Гулмахмад Давлатов',
      '+992 900 11 22 33',
      '',
      'Специалист по сантехнике и электрике. Гипрозем и весь район Сино.',
      ARRAY['Сантехника','Электрика'],
      ARRAY['Сино'],
      12,
      4.9,
      124,
      50,
      300,
      38.5732,
      68.7861,
      96.4,
      124,
      2,
      15,
      45,
      0,
      'good',
      true,
      true
    ),
    (
      'Фаррух Каримов',
      '+992 900 22 33 44',
      '',
      'Электрика любой сложности, установка систем Умный дом в Зарафшоне.',
      ARRAY['Электрика','Умный дом'],
      ARRAY['Сино'],
      10,
      5.0,
      180,
      60,
      400,
      38.5564,
      68.7519,
      99.8,
      180,
      1,
      10,
      60,
      0,
      'good',
      true,
      true
    ),
    (
      'Камол Камолов',
      '+992 900 33 44 55',
      '',
      'Сварочные работы и металлоконструкции. Шохмансур.',
      ARRAY['Сварочные работы','Отделка'],
      ARRAY['Шохмансур'],
      8,
      4.8,
      210,
      100,
      800,
      38.5482,
      68.7794,
      94.5,
      210,
      4,
      20,
      30,
      1,
      'good',
      true,
      true
    ),
    (
      'Рустам Раджабов',
      '+992 900 44 55 66',
      '',
      'Опытный сантехник. Отопление, водоснабжение, канализация.',
      ARRAY['Сантехника','Отопление'],
      ARRAY['Фирдавси'],
      15,
      4.7,
      320,
      80,
      500,
      38.5651,
      68.8012,
      95.7,
      320,
      5,
      18,
      80,
      2,
      'good',
      true,
      true
    ),
    (
      'Алишер Азизов',
      '+992 900 55 66 77',
      '',
      'Монтаж и обслуживание кондиционеров. Фирдавси.',
      ARRAY['Кондиционеры','Отопление'],
      ARRAY['Фирдавси'],
      9,
      4.9,
      150,
      75,
      350,
      38.5920,
      68.8126,
      93.6,
      150,
      3,
      14,
      40,
      0,
      'good',
      true,
      true
    ),
    (
      'Далер Сафаров',
      '+992 900 66 77 88',
      '',
      'Профессиональная уборка и химчистка мебели в Сино.',
      ARRAY['Уборка'],
      ARRAY['Сино'],
      6,
      4.6,
      90,
      40,
      200,
      38.5408,
      68.7688,
      85.9,
      90,
      2,
      25,
      20,
      0,
      'good',
      false,
      true
    ),
    (
      'Комрон Набиев',
      '+992 900 77 88 99',
      '',
      'Видеонаблюдение и домофоны. Район Исмоили Сомони.',
      ARRAY['Видеонаблюдение','Электрика'],
      ARRAY['Исмоили Сомони'],
      7,
      4.8,
      110,
      90,
      600,
      38.5533,
      68.7441,
      91.2,
      110,
      1,
      12,
      25,
      0,
      'good',
      true,
      true
    ),
    (
      'Шохин Абдуллоев',
      '+992 900 88 99 00',
      '',
      'Сборка мебели, установка межкомнатных дверей. Шохмансур.',
      ARRAY['Мебель и двери'],
      ARRAY['Шохмансур'],
      5,
      4.7,
      80,
      55,
      300,
      38.5719,
      68.7586,
      88.8,
      80,
      2,
      20,
      15,
      0,
      'good',
      false,
      true
    ),
    (
      'Джамшед Хакимов',
      '+992 900 99 00 11',
      '',
      'Капитальный ремонт квартир под ключ в Сино.',
      ARRAY['Ремонт под ключ','Отделка'],
      ARRAY['Сино'],
      11,
      4.5,
      60,
      120,
      2000,
      38.5340,
      68.7935,
      82.9,
      60,
      3,
      30,
      10,
      2,
      'good',
      false,
      true
    ),
    (
      'Абдулло Мирзоев',
      '+992 900 00 11 22',
      '',
      'Мастер по плитке и отделочным работам. Фирдавси.',
      ARRAY['Отделка','Плитка'],
      ARRAY['Фирдавси'],
      10,
      4.8,
      140,
      110,
      500,
      38.5602,
      68.7725,
      92.1,
      140,
      2,
      16,
      35,
      1,
      'good',
      true,
      true
    ),
    (
      'Юсуф Бобоев',
      '+992 900 11 22 55',
      '',
      'Мелкий бытовой ремонт, мастер на час в Исмоили Сомони.',
      ARRAY['Другие услуги'],
      ARRAY['Исмоили Сомони'],
      4,
      4.6,
      70,
      35,
      150,
      38.5465,
      68.7842,
      84.3,
      70,
      1,
      15,
      12,
      0,
      'good',
      false,
      true
    ),
    (
      'Саид Алиев',
      '+992 900 22 33 66',
      '',
      'Аварийная служба 24/7. Вскрытие замков, сантехника, электрика.',
      ARRAY['Аварийные 24/7','Электрика','Сантехника'],
      ARRAY['Сино','Фирдавси','Шохмансур','Исмоили Сомони'],
      13,
      4.9,
      200,
      150,
      1000,
      38.5791,
      68.7664,
      98.6,
      200,
      2,
      10,
      50,
      0,
      'good',
      true,
      true
    )
)
INSERT INTO public.master_listings (
  full_name,
  phone,
  avatar_url,
  bio,
  service_categories,
  working_districts,
  experience_years,
  average_rating,
  total_reviews,
  price_min,
  price_max,
  latitude,
  longitude,
  ranking_score,
  completed_orders,
  cancelled_orders,
  response_time_avg,
  repeat_clients,
  complaints,
  quality_flag,
  is_top_master,
  is_active
)
SELECT
  ms.full_name,
  ms.phone,
  ms.avatar_url,
  ms.bio,
  ms.service_categories,
  ms.working_districts,
  ms.experience_years,
  ms.average_rating,
  ms.total_reviews,
  ms.price_min,
  ms.price_max,
  ms.latitude,
  ms.longitude,
  ms.ranking_score,
  ms.completed_orders,
  ms.cancelled_orders,
  ms.response_time_avg,
  ms.repeat_clients,
  ms.complaints,
  ms.quality_flag,
  ms.is_top_master,
  ms.is_active
FROM master_seed ms
ON CONFLICT (full_name, phone) DO UPDATE SET
  bio = EXCLUDED.bio,
  service_categories = EXCLUDED.service_categories,
  working_districts = EXCLUDED.working_districts,
  experience_years = EXCLUDED.experience_years,
  average_rating = EXCLUDED.average_rating,
  total_reviews = EXCLUDED.total_reviews,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  ranking_score = EXCLUDED.ranking_score,
  completed_orders = EXCLUDED.completed_orders,
  is_top_master = EXCLUDED.is_top_master;
